### ISSUE TITLE
Allow slug editing

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/ckanext-versioned-datastore#52]
**Overview**
Sometimes it might be beneficial to edit the default generated slug. For example, when sharing a search on social media.

**Possible Solutions**
There is already a `reserved_pretty_slug` column which can be used for this, we just need to build an interface for it and then decide who can use it.

**Anything Else?**
As an example, I recently modified https://data.nhm.ac.uk/search/green-chance-horse -> https://data.nhm.ac.uk/search/freshwater-insects (`green-chance-horse` remains the `pretty_slug` while `freshwater-insects` was inserted into the `reserved_pretty_slug` column) for Jen before she pushed the link out to Twitter.

**Comment by alycejenni** [comment]
Closed by #61
