### ISSUE TITLE
OR doesn't work

### ISSUE THREAD

**Issue by alycejenni** [NaturalHistoryMuseum/ckanext-versioned-datastore#80]
Using an OR group breaks the search (not valid under any schema).

**Comment by alycejenni** [comment]
Possibly related to #77 since they both raise the same error.

**Comment by jrdh** [comment]
Just tried this again and it worked (https://data.nhm.ac.uk/search/boastfully-dry-beech) but I definitely saw it not work when you flagged this to me. Do you have an broken search for this that I can use @alycejenni ?

**Comment by jrdh** [comment]
Neither of us can reproduce this so closing for now.
