### ISSUE TITLE
Review notes for new downloads

### ISSUE THREAD

**Issue by jrdh** [NaturalHistoryMuseum/ckanext-versioned-datastore#91]
These are review notes from functional user testing of the new downloads code in #89. Will be added to/amended as I go and this list includes questions, bugs and suggestions. I may split them up if it gets too complicated to track what's going on.

- [x] I did a search on everything and got 2 hits, both in specimens (specifically, I searched for "banana" cause I'm a pro) and then triggered a download. When I look on the download status page, under results, it says "Specimen records: 2" and "Index Lots": 0. The download zip also contains an empty index lots csv file
- [x] I managed to get a failure where the error message stored in the database was just the specimen resource id `'05ff2255-c38a-40c9-b657-4ccb55ab2feb'`. All I did was search from the homepage over the specimen collection for "banana" and download. Might have something to do with the previous banana searches I did? Seemed to work fine the next time I tried a new search term.
- [x] How does the extensions select box work in the dwc downloader options UI? It was non-intuitive that I had to ctrl-click to deselect it when there was only one item in the list. I appreciate this is how it works in the browser, but people will complain, I had the same problem in the policy tool and changed it to a list of checkboxes instead.
- [x] It would be nice if on the download page it had "Records Total:" set to calculating or unknown while it's doing the `gen_core` search stage instead of "None".
- [x] I'd also suggest making the status at the top more obviously a status. I didn't spot it initially cause I assumed it was part of the page title "Download status" and just skipped reading it
- [x] I know this page is a temporary thing but it'd be nice if the direct download link had button styling
- [x] #92
- [x] What happens to the existing download database data now that the tables have changed? Is there a migration script?
- [x] We should think about how the download page links to the DOI and visa versa so that it's clear what the relationship between them is (this is something we could think about as part of the search UI too)
- [x] Are DOIs being generated on download still? I haven't seen any in my dev instance get made but it may be a misconfig on my end.

**Comment by alycejenni** [comment]
1. no idea what that's about
2. not sure why you have an error, but the resource id is there because the error message field is also being used to track what's current being processed (so I guess the bit where the actual error message gets inserted didn't work)
3. yeah i need to change that, was done a bit hastily (also needs all the new options adding)
4. k
5. k
6. k
7. nope
8. there will be (it's in progress)
9. yeah, the download page is very barebones atm but that should probably be added somehow
10. gooooood question i don't remember
